apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: m-caj-masterfile
spec:
  hosts:
    - m-caj-masterfile
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage:
          value: 100
    route:
    - destination:
        host: m-caj-masterfile
        subset: v1