apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello-world-task
spec:
  steps:
    - image: image-registry.openshift-image-registry.svc:5000/openshift/ubuntu:22.04
      env:
      - name: HOME
        value: /tekton/home
      script: |
        #!/usr/bin/env bash

        [[ $HOME == /tekton/home ]] && echo "Hello World!!"