apiVersion: v1
kind: Pod
metadata:
  labels:
    run: oc-cli
  name: oc-cli
spec:
  volumes:
  - name: pipeline-data
    persistentVolumeClaim:
      claimName: cli-pv-claim
  containers:
  - image: image-registry.openshift-image-registry.svc:5000/openshift/cli
    imagePullPolicy: Always
    name: oc-cli
    stdin: true
    stdinOnce: true
    tty: true
    securityContext:
      runAsUser: 0
    volumeMounts:
    - mountPath: "/opt/caj"
      name: pipeline-data
  restartPolicy: Always
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cli-pv-claim
spec:
  storageClassName: gp2-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
