apiVersion: v1
kind: Secret
metadata:
  name: github-basic-auth
  annotations:
    tekton.dev/git-0: "{{ .Values.git.url }}"
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.git.username }}"
  password: "{{ .Values.git.accessToken }}"
