apiVersion: v1
kind: Secret
metadata:
  name: quay-basic-auth
  annotations:
    tekton.dev/docker-0: "{{ .Values.registry.url }}"
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.registry.username }}"
  password: "{{ .Values.registry.accessToken }}"