kind: ConfigMap
apiVersion: v1
metadata:
  name: web-config
data:
  config.json: >
    {"masterfileURL":"https://m-caj-masterfile-${PROJECT_NAME}.apps.cluster-zghzl.zghzl.sandbox852.opentlc.com","reservationURL":"https://m-caj-reservation-${PROJECT_NAME}.apps.cluster-zghzl.zghzl.sandbox852.opentlc.com","scheduleURL":"https://m-caj-schedule-${PROJECT_NAME}.apps.cluster-zghzl.zghzl.sandbox852.opentlc.com"}
