kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: m-caj-mock-tvm
spec:
  host: m-caj-mock-tvm-${STUDENT_ID}.${DOMAIN}
  to:
    kind: Service
    name: m-caj-mock-tvm
    weight: 100
  port:
    targetPort: 8080
