kind: ConfigMap
apiVersion: v1
metadata:
  name: web-config
data:
  config.json: >
    {"masterfileURL":"http://${STUDENT_ID}-tvm-app.istio-gateway.apps.cluster-zghzl.zghzl.sandbox852.opentlc.com","reservationURL":"http://${STUDENT_ID}-tvm-app.istio-gateway.apps.cluster-zghzl.zghzl.sandbox852.opentlc.com","scheduleURL":"http://${STUDENT_ID}-tvm-app.istio-gateway.apps.cluster-zghzl.zghzl.sandbox852.opentlc.com"}