apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: m-caj-istio-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - ${STUDENT_ID}-caj-app.istio-gateway.apps.cluster-zghzl.zghzl.sandbox852.opentlc.com
    port:
      name: http
      number: 80
      protocol: HTTP