apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: npm-all-in-one
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: master
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: npm-all-in-one
    taskRef:
      name: npm-all-in-one
      kind: Task
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository