apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npm-all-in-one
spec:
  workspaces:
  - name: source
  steps:
    - name: npm-install
      image: image-registry.openshift-image-registry.svc:5000/openshift/nodejs:16-ubi8
      command: ["/bin/bash", "-c"]
      args:
        - npm install
      workingDir: /workspace/source
    - name: lint
      image: image-registry.openshift-image-registry.svc:5000/openshift/nodejs:16-ubi8
      command: ["/bin/bash", "-c"]
      args:
        - npm run lint
      workingDir: /workspace/source
    - name: test
      image: image-registry.openshift-image-registry.svc:5000/openshift/nodejs:16-ubi8
      command: ["/bin/bash", "-c"]
      args:
        - npm run test
      workingDir: /workspace/source
    - name: build
      image: image-registry.openshift-image-registry.svc:5000/openshift/nodejs:16-ubi8
      command: ["/bin/bash", "-c"]
      args:
        - npm run build
      workingDir: /workspace/source