apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: m-caj-masterfile
spec:
  host: m-caj-masterfile
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2