kind: Deployment
apiVersion: apps/v1
metadata:
  name: m-caj-masterfile-v2
  labels:
    app: m-caj-masterfile
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-caj-masterfile
      version: v2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: m-caj-masterfile
        version: v2
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: m-caj-masterfile
          image: 'quay.io/ske/m-caj-masterfile:latest'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_DIALECT
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_DRIVER
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER
            - name: DB_PXD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PXD
            - name: RELEASE_NO
              value: 2.0.0