apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: m-caj-mono-backend
spec:
  endpoints:
    - interval: 10s
      path: /actuator/prometheus
      port: http
      scheme: http
  selector:
    matchLabels:
      app: m-caj-mono-backend
  targetLabels:
    - app