kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: m-caj-fare
spec:
  host: m-caj-fare-${STUDENT_ID}.${DOMAIN}
  to:
    kind: Service
    name: m-caj-fare
    weight: 100
  port:
    targetPort: 8080