apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: task-refer-git-
spec:
  taskRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/redhat-tw/2023-m-caj.git
    - name: revision
      value: main
    - name: pathInRepo
      value: hands-on/tekton/001-tasks/hello-world/task.yml