kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: m-caj-schedule
spec:
  host: m-caj-schedule-${STUDENT_ID}.apps.cluster-zghzl.zghzl.sandbox852.opentlc.com
  to:
    kind: Service
    name: m-caj-schedule
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None